server {

   listen 443 ssl;
   listen [::]:443 ssl;

   server_name company.local;

   root /var/www/company;
   index index.html;

   ssl_certificate      /etc/nginx/ssl/nginx.crt;
   ssl_certificate_key  /etc/nginx/ssl/nginx.key;

}
